# Generated by Django 5.2 on 2025-04-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_publisher_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='bookshelf.publisher'),
        ),
    ]
